[docker]
    [docker.dockerConfig]
        enable = true
        name = "petstore"
        registry = 'index.docker.io/aaquiff'
    [docker.dockerCopyFiles]
        enable = true
        [[docker.dockerCopyFiles.files]]
            source = '$MICROGW_TOOLKIT_HOME/resources/conf/micro-gw.conf'
            target = '/home/ballerina/conf/micro-gw.conf'
            isBallerinaConf = true
